---
- name: upstart service
  become: true
  template:
    src: "jmx_exporter_httpserver.upstart.j2"
    dest: "/etc/init/jmx_exporter_httpserver.conf"
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify:
    - restart jmx_exporter_httpserver
