---
- name: systemd service
  become: true
  template:
    src: "jmx_exporter_httpserver.systemd.j2"
    dest: "/lib/systemd/system/jmx_exporter_httpserver.service"
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify:
    - reload systemd daemon
    - restart jmx_exporter_httpserver
