---
- name: sysvinit service
  become: true
  template:
    src: "jmx_exporter_httpserver.sysvinit.j2"
    dest: "/etc/init.d/jmx_exporter_httpserver"
    owner: root
    group: root
    mode: "u=rwx,go=rx"
  notify:
    - restart jmx_exporter_httpserver
